name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.head_ref }}-pr

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Git fetch base ref
        run: |
          git fetch --prune --no-tags --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/heads/${{ github.base_ref }}

      - name: SwiftLint
        uses: ezraberch/action-swiftlint@3.2.3
        with:
          args: --strict
        env:
          DIFF_BASE: ${{ github.base_ref }}
          DIFF_HEAD: HEAD

  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.TEST_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.TEST_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.TEST_BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Run unit tests with code coverage
        run: xcodebuild test -scheme ProductivityTest -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' -derivedDataPath Build/ -enableCodeCoverage YES

      - name: Copy xcresult to temp directory
        run: |
          xcresult_path=$(find Build/Logs/Test -name '*.xcresult' | sort | tail -n 1)
          if [ -n "$xcresult_path" ]; then
            new_xcresult_name="TestResult.xcresult"
            temp_path="$RUNNER_TEMP/$new_xcresult_name"
            cp -R "$xcresult_path" "$temp_path"
            echo "xcresult file renamed to $new_xcresult_name and copied to $RUNNER_TEMP"
          else
            echo "No xcresult file found."
          fi

      - name: Check temp directory for copied xcresult
        run: |
          new_xcresult_name="TestResult.xcresult"
          temp_path="$RUNNER_TEMP/$new_xcresult_name"
          if [ -e "$temp_path" ]; then
            echo "$new_xcresult_name exists in $RUNNER_TEMP."
          else
            echo "$new_xcresult_name does not exist in $RUNNER_TEMP."
          fi

      - name: Download xccov-to-sonarqube-generic.sh script
        run: curl -o xccov-to-sonarqube-generic.sh -L https://raw.githubusercontent.com/javierjosefernandes/Productivity/main/xccov-to-sonarqube-generic.sh

      - name: Make xccov-to-sonarqube-generic.sh executable
        run: chmod +x xccov-to-sonarqube-generic.sh

      - name: Convert xcresult to SonarQube generic coverage
        run: ./xccov-to-sonarqube-generic.sh $RUNNER_TEMP/TestResult.xcresult > $RUNNER_TEMP/sonarqube-generic-coverage.xml

      - name: Set up SonarScanner
        run: brew install sonar-scanner

      - name: SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths=$RUNNER_TEMP/sonarqube-generic-coverage.xml \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=-
