name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Install Apple certificate and provisioning profile
        env:
          APPLE_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
          APPLE_DISTRIBUTION_CERTIFICATE_P12_PW: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_P12_PW }}
          APPLE_PROVISION_PROFILE_BASE64_TEST: ${{ secrets.APPLE_PROVISION_PROFILE_BASE64_TEST }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$APPLE_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$APPLE_PROVISION_PROFILE_BASE64_TEST" | base64 --decode -o $PP_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$APPLE_DISTRIBUTION_CERTIFICATE_P12_PW" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Create configuration file
        run: cp Productivity/Configurations/Plist/ConfigTemplate.plist Productivity/Configurations/Plist/ConfigTest.plist

      - name: Fill in configuration file
        env:
          OPEN_AI_API_KEY_TEST: ${{ secrets.OPEN_AI_API_KEY_TEST }}
        run: |
          /usr/libexec/PlistBuddy -c "Set :OpenAIAPIKey '${OPEN_AI_API_KEY_TEST}'" Productivity/Configurations/Plist/ConfigTest.plist

      - name: Run unit tests with code coverage
        run: |
          xcodebuild test \
            -scheme ProductivityTest \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' \
            -derivedDataPath Build/ \
            -enableCodeCoverage YES

      - name: Copy xcresult to temp directory
        run: |
          xcresult_path=$(find Build/Logs/Test -name '*.xcresult' | sort | tail -n 1)
          if [ -n "$xcresult_path" ]; then
            new_xcresult_name="TestResult.xcresult"
            temp_path="$RUNNER_TEMP/$new_xcresult_name"
            cp -R "$xcresult_path" "$temp_path"
            echo "xcresult file renamed to $new_xcresult_name and copied to $RUNNER_TEMP"
          else
            echo "No xcresult file found."
          fi

      - name: Download xccov-to-sonarqube-generic.sh script
        run: curl -o xccov-to-sonarqube-generic.sh -L https://raw.githubusercontent.com/javierjosefernandes/Productivity/main/xccov-to-sonarqube-generic.sh

      - name: Make xccov-to-sonarqube-generic.sh executable
        run: chmod +x xccov-to-sonarqube-generic.sh

      - name: Convert xcresult to SonarQube generic coverage
        run: ./xccov-to-sonarqube-generic.sh $RUNNER_TEMP/TestResult.xcresult > $RUNNER_TEMP/sonarqube-generic-coverage.xml

      - name: Set up SonarScanner
        run: brew install sonar-scanner

      - name: SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths=$RUNNER_TEMP/sonarqube-generic-coverage.xml \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=- \
            -Dsonar.inclusions=Productivity/Sources/**/*
